-- MySQL Script generated by MySQL Workbench
-- Sun Jan 31 22:17:28 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema koreatechEV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema koreatechEV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koreatechEV` DEFAULT CHARACTER SET utf8 ;
USE `koreatechEV` ;

-- -----------------------------------------------------
-- Table `koreatechEV`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koreatechEV`.`student` ;

CREATE TABLE IF NOT EXISTS `koreatechEV`.`student` (
  `user_id` VARCHAR(12) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `name` VARCHAR(5) NOT NULL,
  `nickname` VARCHAR(12) NOT NULL,
  `department` VARCHAR(10) NOT NULL,
  `grade` ENUM('1', '2', '3', '4') NOT NULL,
  `student_number` VARCHAR(10) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `student_number_UNIQUE` (`student_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koreatechEV`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koreatechEV`.`professor` ;

CREATE TABLE IF NOT EXISTS `koreatechEV`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(5) NOT NULL,
  `department` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koreatechEV`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koreatechEV`.`board` ;

CREATE TABLE IF NOT EXISTS `koreatechEV`.`board` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `description` TEXT(2048) NOT NULL,
  `author` VARCHAR(12) NOT NULL,
  `reg_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hit` INT NOT NULL DEFAULT 0,
  `report` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_board_student1_idx` (`author` ASC),
  CONSTRAINT `fk_board_student1`
    FOREIGN KEY (`author`)
    REFERENCES `koreatechEV`.`student` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koreatechEV`.`reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `koreatechEV`.`reply` ;

CREATE TABLE IF NOT EXISTS `koreatechEV`.`reply` (
  `board_id` INT NOT NULL,
  `author` VARCHAR(12) NOT NULL,
  `reg_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descrition` VARCHAR(250) NOT NULL,
  `report` INT NOT NULL DEFAULT 0,
  INDEX `fk_reply_board_idx` (`board_id` ASC),
  CONSTRAINT `fk_reply_board`
    FOREIGN KEY (`board_id`)
    REFERENCES `koreatechEV`.`board` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
